library(arules)
library(arulesViz)
#loading the Data
read.transactions(file.choose(),rm.duplicates = TRUE, format = "basket")
Data<-read.transactions(file.choose(),rm.duplicates = TRUE, sep=",",format = "basket")
#data Exploration
inspect(Data)
length(Data)
size(Data)
LIST(Data)
itemLabels(Data)
summary(Data)
# Data Visualiazation
itemFrequencyPlot(Data,topN=20,popCol="blue",popLwd = 1,main = "Top 20 Transactions")
> itemFrequencyPlot(Data,topN=10, main= "Top 20 Transactions")
itemFrequencyPlot(Data,topN=20, main = "Top 20 Transactions")
image(sample(Data, 20))
image(sample(Data, 20), x<-20,y<-20)
RulesName<- apriori(Data, parameter = list(supp = 0.001, conf = 0.9))
Rulesortbylift<-sort(RulesName,by = "lift")
Rulesortbysupport<-sort(RulesName,by = "support")
Rulesortbyconfidence<-sort(RulesName,by = "confidence")
inspect(Rulesortbylift[1:10])
ItemRules <- subset(RulesName, items %in% "CYBERPOWER Gamer Desktop")
View(RulesName)
View(ItemRules)
inspect(ItemRules)
plot(RulesName)
inspect(RulesName,jitter = 0)
is.redundant(RulesName)
inspect(Rulesortbylift,[1:10])
plot(RulesName, method="paracoord", control=list(reorder=TRUE))
plot(RulesName, method="graph", control=list(type="items")

     